// Generated by: supabase gen types typescript --local > supabase/database.types.ts
// Reflects migrations 20260612000001 .. 20260612000006. Do not hand-edit --
// re-run the generator after any schema migration.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      companies: {
        Row: {
          id: string;
          name: string;
          source: Database["public"]["Enums"]["job_source"];
          board_token: string | null;
          active: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          source: Database["public"]["Enums"]["job_source"];
          board_token?: string | null;
          active?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          source?: Database["public"]["Enums"]["job_source"];
          board_token?: string | null;
          active?: boolean;
          created_at?: string;
        };
        Relationships: [];
      };

      jobs: {
        Row: {
          id: string;
          source: Database["public"]["Enums"]["job_source"];
          source_job_id: string;
          company_id: string | null;
          company_name: string;
          title: string;
          location_raw: string;
          location_tags: Database["public"]["Enums"]["location_tag"][];
          description: string;
          url: string;
          posted_at: string | null;
          first_seen_at: string;
          updated_at: string;
          min_years: number | null;
        };
        Insert: {
          id?: string;
          source: Database["public"]["Enums"]["job_source"];
          source_job_id: string;
          company_id?: string | null;
          company_name: string;
          title: string;
          location_raw?: string;
          location_tags?: Database["public"]["Enums"]["location_tag"][];
          description?: string;
          url: string;
          posted_at?: string | null;
          first_seen_at?: string;
          updated_at?: string;
          min_years?: number | null;
        };
        Update: {
          id?: string;
          source?: Database["public"]["Enums"]["job_source"];
          source_job_id?: string;
          company_id?: string | null;
          company_name?: string;
          title?: string;
          location_raw?: string;
          location_tags?: Database["public"]["Enums"]["location_tag"][];
          description?: string;
          url?: string;
          posted_at?: string | null;
          first_seen_at?: string;
          updated_at?: string;
          min_years?: number | null;
        };
        Relationships: [
          {
            foreignKeyName: "jobs_company_id_fkey";
            columns: ["company_id"];
            isOneToOne: false;
            referencedRelation: "companies";
            referencedColumns: ["id"];
          },
        ];
      };

      resumes: {
        Row: {
          id: string;
          file_path: string;
          parsed_text: string;
          skills: string[];
          uploaded_at: string;
          is_active: boolean;
        };
        Insert: {
          id?: string;
          file_path: string;
          parsed_text?: string;
          skills?: string[];
          uploaded_at?: string;
          is_active?: boolean;
        };
        Update: {
          id?: string;
          file_path?: string;
          parsed_text?: string;
          skills?: string[];
          uploaded_at?: string;
          is_active?: boolean;
        };
        Relationships: [];
      };

      role_selections: {
        Row: {
          id: string;
          primary_role: string;
          expanded_roles: string[];
          created_at: string;
          is_active: boolean;
        };
        Insert: {
          id?: string;
          primary_role: string;
          expanded_roles: string[];
          created_at?: string;
          is_active?: boolean;
        };
        Update: {
          id?: string;
          primary_role?: string;
          expanded_roles?: string[];
          created_at?: string;
          is_active?: boolean;
        };
        Relationships: [];
      };

      role_expansion_map: {
        Row: {
          role: string;
          related_roles: string[];
          source: Database["public"]["Enums"]["role_map_source"];
          updated_at: string;
        };
        Insert: {
          role: string;
          related_roles: string[];
          source: Database["public"]["Enums"]["role_map_source"];
          updated_at?: string;
        };
        Update: {
          role?: string;
          related_roles?: string[];
          source?: Database["public"]["Enums"]["role_map_source"];
          updated_at?: string;
        };
        Relationships: [];
      };

      job_scores: {
        Row: {
          id: string;
          job_id: string;
          role_selection_id: string;
          keyword_score: number;
          ai_score: number | null;
          ai_reasoning: string | null;
          scored_at: string;
        };
        Insert: {
          id?: string;
          job_id: string;
          role_selection_id: string;
          keyword_score: number;
          ai_score?: number | null;
          ai_reasoning?: string | null;
          scored_at?: string;
        };
        Update: {
          id?: string;
          job_id?: string;
          role_selection_id?: string;
          keyword_score?: number;
          ai_score?: number | null;
          ai_reasoning?: string | null;
          scored_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "job_scores_job_id_fkey";
            columns: ["job_id"];
            isOneToOne: false;
            referencedRelation: "jobs";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "job_scores_role_selection_id_fkey";
            columns: ["role_selection_id"];
            isOneToOne: false;
            referencedRelation: "role_selections";
            referencedColumns: ["id"];
          },
        ];
      };

      notifications_log: {
        Row: {
          id: string;
          job_id: string;
          sent_at: string;
        };
        Insert: {
          id?: string;
          job_id: string;
          sent_at?: string;
        };
        Update: {
          id?: string;
          job_id?: string;
          sent_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "notifications_log_job_id_fkey";
            columns: ["job_id"];
            isOneToOne: true;
            referencedRelation: "jobs";
            referencedColumns: ["id"];
          },
        ];
      };

      scrape_runs: {
        Row: {
          id: string;
          source: Database["public"]["Enums"]["job_source"];
          status: Database["public"]["Enums"]["scrape_run_status"];
          jobs_found: number;
          error: string | null;
          run_at: string;
        };
        Insert: {
          id?: string;
          source: Database["public"]["Enums"]["job_source"];
          status: Database["public"]["Enums"]["scrape_run_status"];
          jobs_found?: number;
          error?: string | null;
          run_at?: string;
        };
        Update: {
          id?: string;
          source?: Database["public"]["Enums"]["job_source"];
          status?: Database["public"]["Enums"]["scrape_run_status"];
          jobs_found?: number;
          error?: string | null;
          run_at?: string;
        };
        Relationships: [];
      };

      job_statuses: {
        Row: {
          id: string;
          label: string;
          color: string;
          sort_order: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          label: string;
          color: string;
          sort_order?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          label?: string;
          color?: string;
          sort_order?: number;
          created_at?: string;
        };
        Relationships: [];
      };

      job_state: {
        Row: {
          job_id: string;
          status_id: string | null;
          updated_at: string;
        };
        Insert: {
          job_id: string;
          status_id?: string | null;
          updated_at?: string;
        };
        Update: {
          job_id?: string;
          status_id?: string | null;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "job_state_job_id_fkey";
            columns: ["job_id"];
            isOneToOne: true;
            referencedRelation: "jobs";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "job_state_status_id_fkey";
            columns: ["status_id"];
            isOneToOne: false;
            referencedRelation: "job_statuses";
            referencedColumns: ["id"];
          },
        ];
      };

      app_settings: {
        Row: {
          key: string;
          value: Json;
          updated_at: string;
        };
        Insert: {
          key: string;
          value: Json;
          updated_at?: string;
        };
        Update: {
          key?: string;
          value?: Json;
          updated_at?: string;
        };
        Relationships: [];
      };
    };

    Views: Record<string, never>;

    Functions: {
      set_active_resume: {
        Args: {
          p_file_path: string;
          p_parsed_text: string;
          p_skills: string[];
        };
        Returns: Database["public"]["Tables"]["resumes"]["Row"][];
      };
      set_active_role_selection: {
        Args: {
          p_primary_role: string;
          p_expanded_roles: string[];
        };
        Returns: Database["public"]["Tables"]["role_selections"]["Row"][];
      };
    };

    Enums: {
      job_source: "greenhouse" | "lever" | "ashby" | "wellfound" | "remoteok";
      location_tag: "india" | "singapore" | "uae" | "remote";
      role_map_source: "seed" | "ai";
      scrape_run_status: "success" | "partial" | "failed";
    };

    CompositeTypes: Record<string, never>;
  };
}
