import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardFooter, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import type { RoleMapSource } from "@/shared/domain/enums";

interface ExpandedRolesCardProps {
  relatedRoles: string[];
  source: RoleMapSource;
  onConfirm: () => void;
  isPending: boolean;
  isActive: boolean;
}

export function ExpandedRolesCard({ relatedRoles, source, onConfirm, isPending, isActive }: ExpandedRolesCardProps) {
  return (
    <Card>
      <CardHeader>
        <CardTitle>Related roles</CardTitle>
        <CardDescription>
          {source === "seed" ? "From the saved role map." : "Generated by AI for this role."}
        </CardDescription>
      </CardHeader>
      <CardContent className="flex flex-wrap gap-2">
        {relatedRoles.map((role) => (
          <Badge key={role} variant="secondary">
            {role}
          </Badge>
        ))}
      </CardContent>
      <CardFooter>
        <Button onClick={onConfirm} disabled={isPending || isActive}>
          {isActive ? "Active selection" : isPending ? "Saving..." : "Use this selection"}
        </Button>
      </CardFooter>
    </Card>
  );
}
