import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardFooter, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import type { RoleMapSource } from "@/shared/domain/enums";

interface ExpandedRolesCardProps {
  relatedRoles: string[];
  selectedRoles: string[];
  onToggleRole: (role: string) => void;
  source: RoleMapSource;
  onConfirm: () => void;
  isPending: boolean;
  isActive: boolean;
}

export function ExpandedRolesCard({
  relatedRoles,
  selectedRoles,
  onToggleRole,
  source,
  onConfirm,
  isPending,
  isActive,
}: ExpandedRolesCardProps) {
  return (
    <Card>
      <CardHeader>
        <CardTitle>Related roles</CardTitle>
        <CardDescription>
          {source === "seed" ? "From the saved role map." : "Generated by AI for this role."} Click a role to
          include or exclude it from your selection.
        </CardDescription>
      </CardHeader>
      <CardContent className="flex flex-wrap gap-2">
        {relatedRoles.map((role) => {
          const isSelected = selectedRoles.includes(role);
          return (
            <Badge
              key={role}
              asChild
              variant={isSelected ? "secondary" : "outline"}
              className={isSelected ? "" : "text-muted-foreground"}
            >
              <button
                type="button"
                aria-pressed={isSelected}
                disabled={isPending || isActive}
                onClick={() => onToggleRole(role)}
              >
                {role}
              </button>
            </Badge>
          );
        })}
      </CardContent>
      <CardFooter>
        <Button onClick={onConfirm} disabled={isPending || isActive || selectedRoles.length === 0}>
          {isActive ? "Active selection" : isPending ? "Saving..." : "Use this selection"}
        </Button>
      </CardFooter>
    </Card>
  );
}
